/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  ChatPost200Response,
  ChatPost502Response,
  ChatPostRequest,
} from '../models/index';
import {
    ChatPost200ResponseFromJSON,
    ChatPost200ResponseToJSON,
    ChatPost502ResponseFromJSON,
    ChatPost502ResponseToJSON,
    ChatPostRequestFromJSON,
    ChatPostRequestToJSON,
} from '../models/index';

export interface ChatPostOperationRequest {
    chatPostRequest?: ChatPostRequest;
}

/**
 * 
 */
export class ChatApi extends runtime.BaseAPI {

    /**
     * Send a chat message to the hosted LLM through the backend proxy
     */
    async chatPostRaw(requestParameters: ChatPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<ChatPost200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/chat`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: ChatPostRequestToJSON(requestParameters['chatPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => ChatPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Send a chat message to the hosted LLM through the backend proxy
     */
    async chatPost(requestParameters: ChatPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<ChatPost200Response> {
        const response = await this.chatPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
