/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  HealthzGet200Response,
  HealthzGet503Response,
} from '../models/index';
import {
    HealthzGet200ResponseFromJSON,
    HealthzGet200ResponseToJSON,
    HealthzGet503ResponseFromJSON,
    HealthzGet503ResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class InfraApi extends runtime.BaseAPI {

    /**
     * Health check endpoint
     */
    async healthzGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<HealthzGet200Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/healthz`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => HealthzGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Health check endpoint
     */
    async healthzGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<HealthzGet200Response> {
        const response = await this.healthzGetRaw(initOverrides);
        return await response.value();
    }

}
