/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MazesMazeIdGet200Response,
  MazesMazeIdPathsDslPost200Response,
  MazesMazeIdPathsDslPostRequest,
  MazesMazeIdShortestPathGet200Response,
} from '../models/index';
import {
    MazesMazeIdGet200ResponseFromJSON,
    MazesMazeIdGet200ResponseToJSON,
    MazesMazeIdPathsDslPost200ResponseFromJSON,
    MazesMazeIdPathsDslPost200ResponseToJSON,
    MazesMazeIdPathsDslPostRequestFromJSON,
    MazesMazeIdPathsDslPostRequestToJSON,
    MazesMazeIdShortestPathGet200ResponseFromJSON,
    MazesMazeIdShortestPathGet200ResponseToJSON,
} from '../models/index';

export interface MazesMazeIdGetRequest {
    mazeId: number | null;
}

export interface MazesMazeIdPathsDslPostOperationRequest {
    mazeId: number | null;
    mazesMazeIdPathsDslPostRequest?: MazesMazeIdPathsDslPostRequest;
}

export interface MazesMazeIdShortestPathGetRequest {
    mazeId: number | null;
}

/**
 * 
 */
export class MazesApi extends runtime.BaseAPI {

    /**
     * Retrieve a maze definition
     */
    async mazesMazeIdGetRaw(requestParameters: MazesMazeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MazesMazeIdGet200Response>> {
        if (requestParameters['mazeId'] == null) {
            throw new runtime.RequiredError(
                'mazeId',
                'Required parameter "mazeId" was null or undefined when calling mazesMazeIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mazes/{mazeId}`;
        urlPath = urlPath.replace(`{${"mazeId"}}`, encodeURIComponent(String(requestParameters['mazeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MazesMazeIdGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve a maze definition
     */
    async mazesMazeIdGet(requestParameters: MazesMazeIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MazesMazeIdGet200Response> {
        const response = await this.mazesMazeIdGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Compute the DSL of a specific provided path through the maze.
     */
    async mazesMazeIdPathsDslPostRaw(requestParameters: MazesMazeIdPathsDslPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MazesMazeIdPathsDslPost200Response>> {
        if (requestParameters['mazeId'] == null) {
            throw new runtime.RequiredError(
                'mazeId',
                'Required parameter "mazeId" was null or undefined when calling mazesMazeIdPathsDslPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/mazes/{mazeId}/paths/dsl`;
        urlPath = urlPath.replace(`{${"mazeId"}}`, encodeURIComponent(String(requestParameters['mazeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: MazesMazeIdPathsDslPostRequestToJSON(requestParameters['mazesMazeIdPathsDslPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MazesMazeIdPathsDslPost200ResponseFromJSON(jsonValue));
    }

    /**
     * Compute the DSL of a specific provided path through the maze.
     */
    async mazesMazeIdPathsDslPost(requestParameters: MazesMazeIdPathsDslPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MazesMazeIdPathsDslPost200Response> {
        const response = await this.mazesMazeIdPathsDslPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async mazesMazeIdShortestPathGetRaw(requestParameters: MazesMazeIdShortestPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<MazesMazeIdShortestPathGet200Response>> {
        if (requestParameters['mazeId'] == null) {
            throw new runtime.RequiredError(
                'mazeId',
                'Required parameter "mazeId" was null or undefined when calling mazesMazeIdShortestPathGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/mazes/{mazeId}/shortest-path`;
        urlPath = urlPath.replace(`{${"mazeId"}}`, encodeURIComponent(String(requestParameters['mazeId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => MazesMazeIdShortestPathGet200ResponseFromJSON(jsonValue));
    }

    /**
     */
    async mazesMazeIdShortestPathGet(requestParameters: MazesMazeIdShortestPathGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<MazesMazeIdShortestPathGet200Response> {
        const response = await this.mazesMazeIdShortestPathGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
