/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  MazesMazeIdPathsDslPostRequest,
  SessionsPost201Response,
  SessionsPostRequest,
  SessionsSessionIdPatchRequest,
  SessionsSessionIdPathsGet200Response,
} from '../models/index';
import {
    MazesMazeIdPathsDslPostRequestFromJSON,
    MazesMazeIdPathsDslPostRequestToJSON,
    SessionsPost201ResponseFromJSON,
    SessionsPost201ResponseToJSON,
    SessionsPostRequestFromJSON,
    SessionsPostRequestToJSON,
    SessionsSessionIdPatchRequestFromJSON,
    SessionsSessionIdPatchRequestToJSON,
    SessionsSessionIdPathsGet200ResponseFromJSON,
    SessionsSessionIdPathsGet200ResponseToJSON,
} from '../models/index';

export interface SessionsPostOperationRequest {
    sessionsPostRequest?: SessionsPostRequest;
}

export interface SessionsSessionIdPatchOperationRequest {
    sessionId: string;
    sessionsSessionIdPatchRequest?: SessionsSessionIdPatchRequest;
}

export interface SessionsSessionIdPathsGetRequest {
    sessionId: string;
}

export interface SessionsSessionIdPathsPutRequest {
    sessionId: string;
    mazesMazeIdPathsDslPostRequest?: MazesMazeIdPathsDslPostRequest;
}

/**
 * 
 */
export class SessionsApi extends runtime.BaseAPI {

    /**
     * Create a new session and return a sessionId (and QR payload)
     */
    async sessionsPostRaw(requestParameters: SessionsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsPost201Response>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sessions`;

        const response = await this.request({
            path: urlPath,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: SessionsPostRequestToJSON(requestParameters['sessionsPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionsPost201ResponseFromJSON(jsonValue));
    }

    /**
     * Create a new session and return a sessionId (and QR payload)
     */
    async sessionsPost(requestParameters: SessionsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsPost201Response> {
        const response = await this.sessionsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Update stored information (status, path or expiresAt) for a specific session
     */
    async sessionsSessionIdPatchRaw(requestParameters: SessionsSessionIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsSessionIdPatchRequest>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling sessionsSessionIdPatch().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sessions/{sessionId}`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: SessionsSessionIdPatchRequestToJSON(requestParameters['sessionsSessionIdPatchRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionsSessionIdPatchRequestFromJSON(jsonValue));
    }

    /**
     * Update stored information (status, path or expiresAt) for a specific session
     */
    async sessionsSessionIdPatch(requestParameters: SessionsSessionIdPatchOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsSessionIdPatchRequest> {
        const response = await this.sessionsSessionIdPatchRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Retrieve stored path for a session
     */
    async sessionsSessionIdPathsGetRaw(requestParameters: SessionsSessionIdPathsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsSessionIdPathsGet200Response>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling sessionsSessionIdPathsGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/sessions/{sessionId}/paths`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionsSessionIdPathsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Retrieve stored path for a session
     */
    async sessionsSessionIdPathsGet(requestParameters: SessionsSessionIdPathsGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsSessionIdPathsGet200Response> {
        const response = await this.sessionsSessionIdPathsGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Store a user-selected path and its automatically transpiled DSL representation bund to a session 
     */
    async sessionsSessionIdPathsPutRaw(requestParameters: SessionsSessionIdPathsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<SessionsSessionIdPathsGet200Response>> {
        if (requestParameters['sessionId'] == null) {
            throw new runtime.RequiredError(
                'sessionId',
                'Required parameter "sessionId" was null or undefined when calling sessionsSessionIdPathsPut().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';


        let urlPath = `/sessions/{sessionId}/paths`;
        urlPath = urlPath.replace(`{${"sessionId"}}`, encodeURIComponent(String(requestParameters['sessionId'])));

        const response = await this.request({
            path: urlPath,
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: MazesMazeIdPathsDslPostRequestToJSON(requestParameters['mazesMazeIdPathsDslPostRequest']),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => SessionsSessionIdPathsGet200ResponseFromJSON(jsonValue));
    }

    /**
     * Store a user-selected path and its automatically transpiled DSL representation bund to a session 
     */
    async sessionsSessionIdPathsPut(requestParameters: SessionsSessionIdPathsPutRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<SessionsSessionIdPathsGet200Response> {
        const response = await this.sessionsSessionIdPathsPutRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
