/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatPost200Response
 */
export interface ChatPost200Response {
    /**
     * 
     * @type {string}
     * @memberof ChatPost200Response
     */
    llmAnswer: string;
}

/**
 * Check if a given object implements the ChatPost200Response interface.
 */
export function instanceOfChatPost200Response(value: object): value is ChatPost200Response {
    if (!('llmAnswer' in value) || value['llmAnswer'] === undefined) return false;
    return true;
}

export function ChatPost200ResponseFromJSON(json: any): ChatPost200Response {
    return ChatPost200ResponseFromJSONTyped(json, false);
}

export function ChatPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'llmAnswer': json['llmAnswer'],
    };
}

export function ChatPost200ResponseToJSON(json: any): ChatPost200Response {
    return ChatPost200ResponseToJSONTyped(json, false);
}

export function ChatPost200ResponseToJSONTyped(value?: ChatPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'llmAnswer': value['llmAnswer'],
    };
}

