/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatPost502Response
 */
export interface ChatPost502Response {
    /**
     * 
     * @type {string}
     * @memberof ChatPost502Response
     */
    error: string;
}

/**
 * Check if a given object implements the ChatPost502Response interface.
 */
export function instanceOfChatPost502Response(value: object): value is ChatPost502Response {
    if (!('error' in value) || value['error'] === undefined) return false;
    return true;
}

export function ChatPost502ResponseFromJSON(json: any): ChatPost502Response {
    return ChatPost502ResponseFromJSONTyped(json, false);
}

export function ChatPost502ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatPost502Response {
    if (json == null) {
        return json;
    }
    return {
        
        'error': json['error'],
    };
}

export function ChatPost502ResponseToJSON(json: any): ChatPost502Response {
    return ChatPost502ResponseToJSONTyped(json, false);
}

export function ChatPost502ResponseToJSONTyped(value?: ChatPost502Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'error': value['error'],
    };
}

