/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ChatPostRequest
 */
export interface ChatPostRequest {
    /**
     * 
     * @type {string}
     * @memberof ChatPostRequest
     */
    userMessage: string;
}

/**
 * Check if a given object implements the ChatPostRequest interface.
 */
export function instanceOfChatPostRequest(value: object): value is ChatPostRequest {
    if (!('userMessage' in value) || value['userMessage'] === undefined) return false;
    return true;
}

export function ChatPostRequestFromJSON(json: any): ChatPostRequest {
    return ChatPostRequestFromJSONTyped(json, false);
}

export function ChatPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ChatPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'userMessage': json['userMessage'],
    };
}

export function ChatPostRequestToJSON(json: any): ChatPostRequest {
    return ChatPostRequestToJSONTyped(json, false);
}

export function ChatPostRequestToJSONTyped(value?: ChatPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userMessage': value['userMessage'],
    };
}

