/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthzGet503Response
 */
export interface HealthzGet503Response {
    /**
     * 
     * @type {string}
     * @memberof HealthzGet503Response
     */
    status: HealthzGet503ResponseStatusEnum;
}


/**
 * @export
 */
export const HealthzGet503ResponseStatusEnum = {
    Degraded: 'degraded'
} as const;
export type HealthzGet503ResponseStatusEnum = typeof HealthzGet503ResponseStatusEnum[keyof typeof HealthzGet503ResponseStatusEnum];


/**
 * Check if a given object implements the HealthzGet503Response interface.
 */
export function instanceOfHealthzGet503Response(value: object): value is HealthzGet503Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthzGet503ResponseFromJSON(json: any): HealthzGet503Response {
    return HealthzGet503ResponseFromJSONTyped(json, false);
}

export function HealthzGet503ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthzGet503Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthzGet503ResponseToJSON(json: any): HealthzGet503Response {
    return HealthzGet503ResponseToJSONTyped(json, false);
}

export function HealthzGet503ResponseToJSONTyped(value?: HealthzGet503Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

