/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface HealthzGet200Response
 */
export interface HealthzGet200Response {
    /**
     * 
     * @type {string}
     * @memberof HealthzGet200Response
     */
    status: HealthzGet200ResponseStatusEnum;
}


/**
 * @export
 */
export const HealthzGet200ResponseStatusEnum = {
    Ok: 'ok'
} as const;
export type HealthzGet200ResponseStatusEnum = typeof HealthzGet200ResponseStatusEnum[keyof typeof HealthzGet200ResponseStatusEnum];


/**
 * Check if a given object implements the HealthzGet200Response interface.
 */
export function instanceOfHealthzGet200Response(value: object): value is HealthzGet200Response {
    if (!('status' in value) || value['status'] === undefined) return false;
    return true;
}

export function HealthzGet200ResponseFromJSON(json: any): HealthzGet200Response {
    return HealthzGet200ResponseFromJSONTyped(json, false);
}

export function HealthzGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): HealthzGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'status': json['status'],
    };
}

export function HealthzGet200ResponseToJSON(json: any): HealthzGet200Response {
    return HealthzGet200ResponseToJSONTyped(json, false);
}

export function HealthzGet200ResponseToJSONTyped(value?: HealthzGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'status': value['status'],
    };
}

