/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdGet200ResponseWallsInner } from './MazesMazeIdGet200ResponseWallsInner';
import {
    MazesMazeIdGet200ResponseWallsInnerFromJSON,
    MazesMazeIdGet200ResponseWallsInnerFromJSONTyped,
    MazesMazeIdGet200ResponseWallsInnerToJSON,
    MazesMazeIdGet200ResponseWallsInnerToJSONTyped,
} from './MazesMazeIdGet200ResponseWallsInner';
import type { MazesMazeIdGet200ResponseEdgesInner } from './MazesMazeIdGet200ResponseEdgesInner';
import {
    MazesMazeIdGet200ResponseEdgesInnerFromJSON,
    MazesMazeIdGet200ResponseEdgesInnerFromJSONTyped,
    MazesMazeIdGet200ResponseEdgesInnerToJSON,
    MazesMazeIdGet200ResponseEdgesInnerToJSONTyped,
} from './MazesMazeIdGet200ResponseEdgesInner';
import type { MazesMazeIdGet200ResponseNodesInner } from './MazesMazeIdGet200ResponseNodesInner';
import {
    MazesMazeIdGet200ResponseNodesInnerFromJSON,
    MazesMazeIdGet200ResponseNodesInnerFromJSONTyped,
    MazesMazeIdGet200ResponseNodesInnerToJSON,
    MazesMazeIdGet200ResponseNodesInnerToJSONTyped,
} from './MazesMazeIdGet200ResponseNodesInner';

/**
 * 
 * @export
 * @interface MazesMazeIdGet200Response
 */
export interface MazesMazeIdGet200Response {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdGet200Response
     */
    mazeId: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdGet200Response
     */
    startNodeId: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdGet200Response
     */
    endNodeId: number;
    /**
     * 
     * @type {Array<MazesMazeIdGet200ResponseNodesInner>}
     * @memberof MazesMazeIdGet200Response
     */
    nodes: Array<MazesMazeIdGet200ResponseNodesInner>;
    /**
     * 
     * @type {Array<MazesMazeIdGet200ResponseEdgesInner>}
     * @memberof MazesMazeIdGet200Response
     */
    edges: Array<MazesMazeIdGet200ResponseEdgesInner>;
    /**
     * 
     * @type {Array<MazesMazeIdGet200ResponseWallsInner>}
     * @memberof MazesMazeIdGet200Response
     */
    walls?: Array<MazesMazeIdGet200ResponseWallsInner>;
}

/**
 * Check if a given object implements the MazesMazeIdGet200Response interface.
 */
export function instanceOfMazesMazeIdGet200Response(value: object): value is MazesMazeIdGet200Response {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('startNodeId' in value) || value['startNodeId'] === undefined) return false;
    if (!('endNodeId' in value) || value['endNodeId'] === undefined) return false;
    if (!('nodes' in value) || value['nodes'] === undefined) return false;
    if (!('edges' in value) || value['edges'] === undefined) return false;
    return true;
}

export function MazesMazeIdGet200ResponseFromJSON(json: any): MazesMazeIdGet200Response {
    return MazesMazeIdGet200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'startNodeId': json['startNodeId'],
        'endNodeId': json['endNodeId'],
        'nodes': ((json['nodes'] as Array<any>).map(MazesMazeIdGet200ResponseNodesInnerFromJSON)),
        'edges': ((json['edges'] as Array<any>).map(MazesMazeIdGet200ResponseEdgesInnerFromJSON)),
        'walls': json['walls'] == null ? undefined : ((json['walls'] as Array<any>).map(MazesMazeIdGet200ResponseWallsInnerFromJSON)),
    };
}

export function MazesMazeIdGet200ResponseToJSON(json: any): MazesMazeIdGet200Response {
    return MazesMazeIdGet200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdGet200ResponseToJSONTyped(value?: MazesMazeIdGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'startNodeId': value['startNodeId'],
        'endNodeId': value['endNodeId'],
        'nodes': ((value['nodes'] as Array<any>).map(MazesMazeIdGet200ResponseNodesInnerToJSON)),
        'edges': ((value['edges'] as Array<any>).map(MazesMazeIdGet200ResponseEdgesInnerToJSON)),
        'walls': value['walls'] == null ? undefined : ((value['walls'] as Array<any>).map(MazesMazeIdGet200ResponseWallsInnerToJSON)),
    };
}

