/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayFeedGet200ResponseLeaderboardInner } from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInner';
import {
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerFromJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerFromJSONTyped,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerToJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerToJSONTyped,
} from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInner';

/**
 * 
 * @export
 * @interface MazesMazeIdDisplayFeedGet200Response
 */
export interface MazesMazeIdDisplayFeedGet200Response {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayFeedGet200Response
     */
    mazeId: number;
    /**
     * 
     * @type {Date}
     * @memberof MazesMazeIdDisplayFeedGet200Response
     */
    generatedAt: Date;
    /**
     * 
     * @type {Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInner>}
     * @memberof MazesMazeIdDisplayFeedGet200Response
     */
    leaderboard: Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInner>;
}

/**
 * Check if a given object implements the MazesMazeIdDisplayFeedGet200Response interface.
 */
export function instanceOfMazesMazeIdDisplayFeedGet200Response(value: object): value is MazesMazeIdDisplayFeedGet200Response {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('leaderboard' in value) || value['leaderboard'] === undefined) return false;
    return true;
}

export function MazesMazeIdDisplayFeedGet200ResponseFromJSON(json: any): MazesMazeIdDisplayFeedGet200Response {
    return MazesMazeIdDisplayFeedGet200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdDisplayFeedGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdDisplayFeedGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'generatedAt': (new Date(json['generatedAt'])),
        'leaderboard': ((json['leaderboard'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerFromJSON)),
    };
}

export function MazesMazeIdDisplayFeedGet200ResponseToJSON(json: any): MazesMazeIdDisplayFeedGet200Response {
    return MazesMazeIdDisplayFeedGet200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdDisplayFeedGet200ResponseToJSONTyped(value?: MazesMazeIdDisplayFeedGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'generatedAt': value['generatedAt'].toISOString(),
        'leaderboard': ((value['leaderboard'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerToJSON)),
    };
}

