/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayNextGet200ResponseAnimation } from './MazesMazeIdDisplayNextGet200ResponseAnimation';
import {
    MazesMazeIdDisplayNextGet200ResponseAnimationFromJSON,
    MazesMazeIdDisplayNextGet200ResponseAnimationFromJSONTyped,
    MazesMazeIdDisplayNextGet200ResponseAnimationToJSON,
    MazesMazeIdDisplayNextGet200ResponseAnimationToJSONTyped,
} from './MazesMazeIdDisplayNextGet200ResponseAnimation';

/**
 * 
 * @export
 * @interface MazesMazeIdDisplayNextGet200Response
 */
export interface MazesMazeIdDisplayNextGet200Response {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200Response
     */
    mazeId: number;
    /**
     * 
     * @type {Date}
     * @memberof MazesMazeIdDisplayNextGet200Response
     */
    generatedAt: Date;
    /**
     * 
     * @type {MazesMazeIdDisplayNextGet200ResponseAnimation}
     * @memberof MazesMazeIdDisplayNextGet200Response
     */
    animation: MazesMazeIdDisplayNextGet200ResponseAnimation | null;
}

/**
 * Check if a given object implements the MazesMazeIdDisplayNextGet200Response interface.
 */
export function instanceOfMazesMazeIdDisplayNextGet200Response(value: object): value is MazesMazeIdDisplayNextGet200Response {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('generatedAt' in value) || value['generatedAt'] === undefined) return false;
    if (!('animation' in value) || value['animation'] === undefined) return false;
    return true;
}

export function MazesMazeIdDisplayNextGet200ResponseFromJSON(json: any): MazesMazeIdDisplayNextGet200Response {
    return MazesMazeIdDisplayNextGet200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdDisplayNextGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdDisplayNextGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'generatedAt': (new Date(json['generatedAt'])),
        'animation': MazesMazeIdDisplayNextGet200ResponseAnimationFromJSON(json['animation']),
    };
}

export function MazesMazeIdDisplayNextGet200ResponseToJSON(json: any): MazesMazeIdDisplayNextGet200Response {
    return MazesMazeIdDisplayNextGet200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdDisplayNextGet200ResponseToJSONTyped(value?: MazesMazeIdDisplayNextGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'generatedAt': value['generatedAt'].toISOString(),
        'animation': MazesMazeIdDisplayNextGet200ResponseAnimationToJSON(value['animation']),
    };
}

