/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner } from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';
import {
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped,
} from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';

/**
 * 
 * @export
 * @interface MazesMazeIdDisplayNextGet200ResponseAnimation
 */
export interface MazesMazeIdDisplayNextGet200ResponseAnimation {
    /**
     * 
     * @type {string}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    userName: string;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    mazeId: number;
    /**
     * 
     * @type {Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    path: Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    elapsedMs: number;
    /**
     * 
     * @type {Date}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    submittedAt: Date;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    rank: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    moveCount: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayNextGet200ResponseAnimation
     */
    pathLength: number;
}

/**
 * Check if a given object implements the MazesMazeIdDisplayNextGet200ResponseAnimation interface.
 */
export function instanceOfMazesMazeIdDisplayNextGet200ResponseAnimation(value: object): value is MazesMazeIdDisplayNextGet200ResponseAnimation {
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('elapsedMs' in value) || value['elapsedMs'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    if (!('rank' in value) || value['rank'] === undefined) return false;
    if (!('moveCount' in value) || value['moveCount'] === undefined) return false;
    if (!('pathLength' in value) || value['pathLength'] === undefined) return false;
    return true;
}

export function MazesMazeIdDisplayNextGet200ResponseAnimationFromJSON(json: any): MazesMazeIdDisplayNextGet200ResponseAnimation {
    return MazesMazeIdDisplayNextGet200ResponseAnimationFromJSONTyped(json, false);
}

export function MazesMazeIdDisplayNextGet200ResponseAnimationFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdDisplayNextGet200ResponseAnimation {
    if (json == null) {
        return json;
    }
    return {
        
        'userName': json['userName'],
        'mazeId': json['mazeId'],
        'path': ((json['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON)),
        'elapsedMs': json['elapsedMs'],
        'submittedAt': (new Date(json['submittedAt'])),
        'rank': json['rank'],
        'moveCount': json['moveCount'],
        'pathLength': json['pathLength'],
    };
}

export function MazesMazeIdDisplayNextGet200ResponseAnimationToJSON(json: any): MazesMazeIdDisplayNextGet200ResponseAnimation {
    return MazesMazeIdDisplayNextGet200ResponseAnimationToJSONTyped(json, false);
}

export function MazesMazeIdDisplayNextGet200ResponseAnimationToJSONTyped(value?: MazesMazeIdDisplayNextGet200ResponseAnimation | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'userName': value['userName'],
        'mazeId': value['mazeId'],
        'path': ((value['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON)),
        'elapsedMs': value['elapsedMs'],
        'submittedAt': value['submittedAt'].toISOString(),
        'rank': value['rank'],
        'moveCount': value['moveCount'],
        'pathLength': value['pathLength'],
    };
}

