/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner
 */
export interface MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner
     */
    y: number;
}

/**
 * Check if a given object implements the MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner interface.
 */
export function instanceOfMazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner(value: object): value is MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON(json: any): MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner {
    return MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped(json, false);
}

export function MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON(json: any): MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner {
    return MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped(json, false);
}

export function MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped(value?: MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

