/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdPathsDslPostRequestPathInner } from './MazesMazeIdPathsDslPostRequestPathInner';
import {
    MazesMazeIdPathsDslPostRequestPathInnerFromJSON,
    MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped,
    MazesMazeIdPathsDslPostRequestPathInnerToJSON,
    MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped,
} from './MazesMazeIdPathsDslPostRequestPathInner';

/**
 * 
 * @export
 * @interface MazesMazeIdPathsDslPostRequest
 */
export interface MazesMazeIdPathsDslPostRequest {
    /**
     * 
     * @type {Array<MazesMazeIdPathsDslPostRequestPathInner>}
     * @memberof MazesMazeIdPathsDslPostRequest
     */
    path: Array<MazesMazeIdPathsDslPostRequestPathInner>;
}

/**
 * Check if a given object implements the MazesMazeIdPathsDslPostRequest interface.
 */
export function instanceOfMazesMazeIdPathsDslPostRequest(value: object): value is MazesMazeIdPathsDslPostRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    return true;
}

export function MazesMazeIdPathsDslPostRequestFromJSON(json: any): MazesMazeIdPathsDslPostRequest {
    return MazesMazeIdPathsDslPostRequestFromJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdPathsDslPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': ((json['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerFromJSON)),
    };
}

export function MazesMazeIdPathsDslPostRequestToJSON(json: any): MazesMazeIdPathsDslPostRequest {
    return MazesMazeIdPathsDslPostRequestToJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPostRequestToJSONTyped(value?: MazesMazeIdPathsDslPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': ((value['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerToJSON)),
    };
}

