/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdPathsDslPostRequestPathInner } from './MazesMazeIdPathsDslPostRequestPathInner';
import {
    MazesMazeIdPathsDslPostRequestPathInnerFromJSON,
    MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped,
    MazesMazeIdPathsDslPostRequestPathInnerToJSON,
    MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped,
} from './MazesMazeIdPathsDslPostRequestPathInner';
import type { MazesMazeIdShortestPathGet200ResponseExplorationStepsInner } from './MazesMazeIdShortestPathGet200ResponseExplorationStepsInner';
import {
    MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSON,
    MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSONTyped,
    MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSON,
    MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSONTyped,
} from './MazesMazeIdShortestPathGet200ResponseExplorationStepsInner';

/**
 * 
 * @export
 * @interface MazesMazeIdShortestPathGet200Response
 */
export interface MazesMazeIdShortestPathGet200Response {
    /**
     * 
     * @type {string}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    algorithm: MazesMazeIdShortestPathGet200ResponseAlgorithmEnum;
    /**
     * 
     * @type {Array<MazesMazeIdPathsDslPostRequestPathInner>}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    path: Array<MazesMazeIdPathsDslPostRequestPathInner>;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    length: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    cost: number;
    /**
     * 
     * @type {Array<MazesMazeIdShortestPathGet200ResponseExplorationStepsInner>}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    explorationSteps: Array<MazesMazeIdShortestPathGet200ResponseExplorationStepsInner>;
}


/**
 * @export
 */
export const MazesMazeIdShortestPathGet200ResponseAlgorithmEnum = {
    Bfs: 'bfs',
    Dijkstra: 'dijkstra'
} as const;
export type MazesMazeIdShortestPathGet200ResponseAlgorithmEnum = typeof MazesMazeIdShortestPathGet200ResponseAlgorithmEnum[keyof typeof MazesMazeIdShortestPathGet200ResponseAlgorithmEnum];


/**
 * Check if a given object implements the MazesMazeIdShortestPathGet200Response interface.
 */
export function instanceOfMazesMazeIdShortestPathGet200Response(value: object): value is MazesMazeIdShortestPathGet200Response {
    if (!('algorithm' in value) || value['algorithm'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    if (!('cost' in value) || value['cost'] === undefined) return false;
    if (!('explorationSteps' in value) || value['explorationSteps'] === undefined) return false;
    return true;
}

export function MazesMazeIdShortestPathGet200ResponseFromJSON(json: any): MazesMazeIdShortestPathGet200Response {
    return MazesMazeIdShortestPathGet200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdShortestPathGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'algorithm': json['algorithm'],
        'path': ((json['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerFromJSON)),
        'length': json['length'],
        'cost': json['cost'],
        'explorationSteps': ((json['explorationSteps'] as Array<any>).map(MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSON)),
    };
}

export function MazesMazeIdShortestPathGet200ResponseToJSON(json: any): MazesMazeIdShortestPathGet200Response {
    return MazesMazeIdShortestPathGet200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseToJSONTyped(value?: MazesMazeIdShortestPathGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'algorithm': value['algorithm'],
        'path': ((value['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerToJSON)),
        'length': value['length'],
        'cost': value['cost'],
        'explorationSteps': ((value['explorationSteps'] as Array<any>).map(MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSON)),
    };
}

