/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MazesMazeIdGet200ResponseWallsInner
 */
export interface MazesMazeIdGet200ResponseWallsInner {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdGet200ResponseWallsInner
     */
    from: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdGet200ResponseWallsInner
     */
    to: number;
}

/**
 * Check if a given object implements the MazesMazeIdGet200ResponseWallsInner interface.
 */
export function instanceOfMazesMazeIdGet200ResponseWallsInner(value: object): value is MazesMazeIdGet200ResponseWallsInner {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    return true;
}

export function MazesMazeIdGet200ResponseWallsInnerFromJSON(json: any): MazesMazeIdGet200ResponseWallsInner {
    return MazesMazeIdGet200ResponseWallsInnerFromJSONTyped(json, false);
}

export function MazesMazeIdGet200ResponseWallsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdGet200ResponseWallsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'from': json['from'],
        'to': json['to'],
    };
}

export function MazesMazeIdGet200ResponseWallsInnerToJSON(json: any): MazesMazeIdGet200ResponseWallsInner {
    return MazesMazeIdGet200ResponseWallsInnerToJSONTyped(json, false);
}

export function MazesMazeIdGet200ResponseWallsInnerToJSONTyped(value?: MazesMazeIdGet200ResponseWallsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': value['from'],
        'to': value['to'],
    };
}

