/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner } from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';
import {
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped,
} from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';

/**
 * 
 * @export
 * @interface MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
 */
export interface MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    /**
     * 
     * @type {MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    from: MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner;
    /**
     * 
     * @type {MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    to: MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner;
    /**
     * 
     * @type {boolean}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    discovered: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    improved: boolean;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    candidateCost: number;
}

/**
 * Check if a given object implements the MazesMazeIdShortestPathGet200ResponseExplorationStepsInner interface.
 */
export function instanceOfMazesMazeIdShortestPathGet200ResponseExplorationStepsInner(value: object): value is MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    if (!('from' in value) || value['from'] === undefined) return false;
    if (!('to' in value) || value['to'] === undefined) return false;
    if (!('discovered' in value) || value['discovered'] === undefined) return false;
    if (!('improved' in value) || value['improved'] === undefined) return false;
    if (!('candidateCost' in value) || value['candidateCost'] === undefined) return false;
    return true;
}

export function MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSON(json: any): MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    return MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    if (json == null) {
        return json;
    }
    return {
        
        'from': MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON(json['from']),
        'to': MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON(json['to']),
        'discovered': json['discovered'],
        'improved': json['improved'],
        'candidateCost': json['candidateCost'],
    };
}

export function MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSON(json: any): MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    return MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseExplorationStepsInnerToJSONTyped(value?: MazesMazeIdShortestPathGet200ResponseExplorationStepsInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'from': MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON(value['from']),
        'to': MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON(value['to']),
        'discovered': value['discovered'],
        'improved': value['improved'],
        'candidateCost': value['candidateCost'],
    };
}

