/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MazesMazeIdPathsDslPost200Response
 */
export interface MazesMazeIdPathsDslPost200Response {
    /**
     * 
     * @type {Array<string>}
     * @memberof MazesMazeIdPathsDslPost200Response
     */
    dsl: Array<string>;
}

/**
 * Check if a given object implements the MazesMazeIdPathsDslPost200Response interface.
 */
export function instanceOfMazesMazeIdPathsDslPost200Response(value: object): value is MazesMazeIdPathsDslPost200Response {
    if (!('dsl' in value) || value['dsl'] === undefined) return false;
    return true;
}

export function MazesMazeIdPathsDslPost200ResponseFromJSON(json: any): MazesMazeIdPathsDslPost200Response {
    return MazesMazeIdPathsDslPost200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPost200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdPathsDslPost200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'dsl': json['dsl'],
    };
}

export function MazesMazeIdPathsDslPost200ResponseToJSON(json: any): MazesMazeIdPathsDslPost200Response {
    return MazesMazeIdPathsDslPost200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPost200ResponseToJSONTyped(value?: MazesMazeIdPathsDslPost200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'dsl': value['dsl'],
    };
}

