/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface MazesMazeIdPathsDslPostRequestPathInner
 */
export interface MazesMazeIdPathsDslPostRequestPathInner {
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdPathsDslPostRequestPathInner
     */
    x: number;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdPathsDslPostRequestPathInner
     */
    y: number;
}

/**
 * Check if a given object implements the MazesMazeIdPathsDslPostRequestPathInner interface.
 */
export function instanceOfMazesMazeIdPathsDslPostRequestPathInner(value: object): value is MazesMazeIdPathsDslPostRequestPathInner {
    if (!('x' in value) || value['x'] === undefined) return false;
    if (!('y' in value) || value['y'] === undefined) return false;
    return true;
}

export function MazesMazeIdPathsDslPostRequestPathInnerFromJSON(json: any): MazesMazeIdPathsDslPostRequestPathInner {
    return MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdPathsDslPostRequestPathInner {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function MazesMazeIdPathsDslPostRequestPathInnerToJSON(json: any): MazesMazeIdPathsDslPostRequestPathInner {
    return MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped(json, false);
}

export function MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped(value?: MazesMazeIdPathsDslPostRequestPathInner | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

