/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdPathsDslPostRequestPathInner } from './MazesMazeIdPathsDslPostRequestPathInner';
import {
    MazesMazeIdPathsDslPostRequestPathInnerFromJSON,
    MazesMazeIdPathsDslPostRequestPathInnerToJSON,
} from './MazesMazeIdPathsDslPostRequestPathInner';

/**
 *
 * @export
 * @interface MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
 */
export interface MazesMazeIdShortestPathGet200ResponseExplorationStepsInner {
    /**
     *
     * @type {MazesMazeIdPathsDslPostRequestPathInner}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    from: MazesMazeIdPathsDslPostRequestPathInner;
    /**
     *
     * @type {MazesMazeIdPathsDslPostRequestPathInner}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    to: MazesMazeIdPathsDslPostRequestPathInner;
    /**
     *
     * @type {boolean}
     * @memberof MazesMazeIdShortestPathGet200ResponseExplorationStepsInner
     */
    discovered: boolean;
}

/**
 * 
 * @export
 * @interface MazesMazeIdShortestPathGet200Response
 */
export interface MazesMazeIdShortestPathGet200Response {
    /**
     * 
     * @type {Array<MazesMazeIdPathsDslPostRequestPathInner>}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    path: Array<MazesMazeIdPathsDslPostRequestPathInner>;
    /**
     *
     * @type {Array<MazesMazeIdShortestPathGet200ResponseExplorationStepsInner>}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    explorationSteps: Array<MazesMazeIdShortestPathGet200ResponseExplorationStepsInner>;
    /**
     * 
     * @type {number}
     * @memberof MazesMazeIdShortestPathGet200Response
     */
    length: number;
}

/**
 * Check if a given object implements the MazesMazeIdShortestPathGet200Response interface.
 */
export function instanceOfMazesMazeIdShortestPathGet200Response(value: object): value is MazesMazeIdShortestPathGet200Response {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('explorationSteps' in value) || value['explorationSteps'] === undefined) return false;
    if (!('length' in value) || value['length'] === undefined) return false;
    return true;
}

export function MazesMazeIdShortestPathGet200ResponseFromJSON(json: any): MazesMazeIdShortestPathGet200Response {
    return MazesMazeIdShortestPathGet200ResponseFromJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): MazesMazeIdShortestPathGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'path': ((json['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerFromJSON)),
        'explorationSteps': ((json['explorationSteps'] as Array<any>).map((value: any) => ({
            'from': MazesMazeIdPathsDslPostRequestPathInnerFromJSON(value['from']),
            'to': MazesMazeIdPathsDslPostRequestPathInnerFromJSON(value['to']),
            'discovered': value['discovered'],
        }))),
        'length': json['length'],
    };
}

export function MazesMazeIdShortestPathGet200ResponseToJSON(json: any): MazesMazeIdShortestPathGet200Response {
    return MazesMazeIdShortestPathGet200ResponseToJSONTyped(json, false);
}

export function MazesMazeIdShortestPathGet200ResponseToJSONTyped(value?: MazesMazeIdShortestPathGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': ((value['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerToJSON)),
        'explorationSteps': ((value['explorationSteps'] as Array<any>).map((value: any) => ({
            'from': MazesMazeIdPathsDslPostRequestPathInnerToJSON(value['from']),
            'to': MazesMazeIdPathsDslPostRequestPathInnerToJSON(value['to']),
            'discovered': value['discovered'],
        }))),
        'length': value['length'],
    };
}
