/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdPathsDslPostRequestPathInner } from './MazesMazeIdPathsDslPostRequestPathInner';
import {
    MazesMazeIdPathsDslPostRequestPathInnerFromJSON,
    MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped,
    MazesMazeIdPathsDslPostRequestPathInnerToJSON,
    MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped,
} from './MazesMazeIdPathsDslPostRequestPathInner';

/**
 * 
 * @export
 * @interface SessionsSessionIdPathsPutRequest
 */
export interface SessionsSessionIdPathsPutRequest {
    /**
     * 
     * @type {Array<MazesMazeIdPathsDslPostRequestPathInner>}
     * @memberof SessionsSessionIdPathsPutRequest
     */
    path: Array<MazesMazeIdPathsDslPostRequestPathInner>;
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPathsPutRequest
     */
    elapsedMs: number;
}

/**
 * Check if a given object implements the SessionsSessionIdPathsPutRequest interface.
 */
export function instanceOfSessionsSessionIdPathsPutRequest(value: object): value is SessionsSessionIdPathsPutRequest {
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('elapsedMs' in value) || value['elapsedMs'] === undefined) return false;
    return true;
}

export function SessionsSessionIdPathsPutRequestFromJSON(json: any): SessionsSessionIdPathsPutRequest {
    return SessionsSessionIdPathsPutRequestFromJSONTyped(json, false);
}

export function SessionsSessionIdPathsPutRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsSessionIdPathsPutRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'path': ((json['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerFromJSON)),
        'elapsedMs': json['elapsedMs'],
    };
}

export function SessionsSessionIdPathsPutRequestToJSON(json: any): SessionsSessionIdPathsPutRequest {
    return SessionsSessionIdPathsPutRequestToJSONTyped(json, false);
}

export function SessionsSessionIdPathsPutRequestToJSONTyped(value?: SessionsSessionIdPathsPutRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'path': ((value['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerToJSON)),
        'elapsedMs': value['elapsedMs'],
    };
}

