/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdPathsDslPostRequestPathInner } from './MazesMazeIdPathsDslPostRequestPathInner';
import {
    MazesMazeIdPathsDslPostRequestPathInnerFromJSON,
    MazesMazeIdPathsDslPostRequestPathInnerFromJSONTyped,
    MazesMazeIdPathsDslPostRequestPathInnerToJSON,
    MazesMazeIdPathsDslPostRequestPathInnerToJSONTyped,
} from './MazesMazeIdPathsDslPostRequestPathInner';

/**
 * 
 * @export
 * @interface SessionsSessionIdPathsGet200Response
 */
export interface SessionsSessionIdPathsGet200Response {
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPathsGet200Response
     */
    mazeId: number;
    /**
     * 
     * @type {Array<MazesMazeIdPathsDslPostRequestPathInner>}
     * @memberof SessionsSessionIdPathsGet200Response
     */
    path: Array<MazesMazeIdPathsDslPostRequestPathInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SessionsSessionIdPathsGet200Response
     */
    dsl: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPathsGet200Response
     */
    elapsedMs: number;
}

/**
 * Check if a given object implements the SessionsSessionIdPathsGet200Response interface.
 */
export function instanceOfSessionsSessionIdPathsGet200Response(value: object): value is SessionsSessionIdPathsGet200Response {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('dsl' in value) || value['dsl'] === undefined) return false;
    if (!('elapsedMs' in value) || value['elapsedMs'] === undefined) return false;
    return true;
}

export function SessionsSessionIdPathsGet200ResponseFromJSON(json: any): SessionsSessionIdPathsGet200Response {
    return SessionsSessionIdPathsGet200ResponseFromJSONTyped(json, false);
}

export function SessionsSessionIdPathsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsSessionIdPathsGet200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'path': ((json['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerFromJSON)),
        'dsl': json['dsl'],
        'elapsedMs': json['elapsedMs'],
    };
}

export function SessionsSessionIdPathsGet200ResponseToJSON(json: any): SessionsSessionIdPathsGet200Response {
    return SessionsSessionIdPathsGet200ResponseToJSONTyped(json, false);
}

export function SessionsSessionIdPathsGet200ResponseToJSONTyped(value?: SessionsSessionIdPathsGet200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'path': ((value['path'] as Array<any>).map(MazesMazeIdPathsDslPostRequestPathInnerToJSON)),
        'dsl': value['dsl'],
        'elapsedMs': value['elapsedMs'],
    };
}

