/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionsPostRequest
 */
export interface SessionsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionsPostRequest
     */
    mazeId: number;
}

/**
 * Check if a given object implements the SessionsPostRequest interface.
 */
export function instanceOfSessionsPostRequest(value: object): value is SessionsPostRequest {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    return true;
}

export function SessionsPostRequestFromJSON(json: any): SessionsPostRequest {
    return SessionsPostRequestFromJSONTyped(json, false);
}

export function SessionsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
    };
}

export function SessionsPostRequestToJSON(json: any): SessionsPostRequest {
    return SessionsPostRequestToJSONTyped(json, false);
}

export function SessionsPostRequestToJSONTyped(value?: SessionsPostRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
    };
}

