/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SessionsPost201Response
 */
export interface SessionsPost201Response {
    /**
     * 
     * @type {string}
     * @memberof SessionsPost201Response
     */
    sessionId: string;
    /**
     * 
     * @type {string}
     * @memberof SessionsPost201Response
     */
    userName: string;
    /**
     * 
     * @type {string}
     * @memberof SessionsPost201Response
     */
    qrPayload: string;
}

/**
 * Check if a given object implements the SessionsPost201Response interface.
 */
export function instanceOfSessionsPost201Response(value: object): value is SessionsPost201Response {
    if (!('sessionId' in value) || value['sessionId'] === undefined) return false;
    if (!('userName' in value) || value['userName'] === undefined) return false;
    if (!('qrPayload' in value) || value['qrPayload'] === undefined) return false;
    return true;
}

export function SessionsPost201ResponseFromJSON(json: any): SessionsPost201Response {
    return SessionsPost201ResponseFromJSONTyped(json, false);
}

export function SessionsPost201ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsPost201Response {
    if (json == null) {
        return json;
    }
    return {
        
        'sessionId': json['sessionId'],
        'userName': json['userName'],
        'qrPayload': json['qrPayload'],
    };
}

export function SessionsPost201ResponseToJSON(json: any): SessionsPost201Response {
    return SessionsPost201ResponseToJSONTyped(json, false);
}

export function SessionsPost201ResponseToJSONTyped(value?: SessionsPost201Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'sessionId': value['sessionId'],
        'userName': value['userName'],
        'qrPayload': value['qrPayload'],
    };
}
