/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner } from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';
import {
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped,
} from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';

/**
 * 
 * @export
 * @interface SessionsSessionIdPathsPut200Response
 */
export interface SessionsSessionIdPathsPut200Response {
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPathsPut200Response
     */
    mazeId: number;
    /**
     * 
     * @type {Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>}
     * @memberof SessionsSessionIdPathsPut200Response
     */
    path: Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>;
    /**
     * 
     * @type {Array<string>}
     * @memberof SessionsSessionIdPathsPut200Response
     */
    dsl: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPathsPut200Response
     */
    elapsedMs: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionsSessionIdPathsPut200Response
     */
    submittedAt: Date;
}

/**
 * Check if a given object implements the SessionsSessionIdPathsPut200Response interface.
 */
export function instanceOfSessionsSessionIdPathsPut200Response(value: object): value is SessionsSessionIdPathsPut200Response {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    if (!('path' in value) || value['path'] === undefined) return false;
    if (!('dsl' in value) || value['dsl'] === undefined) return false;
    if (!('elapsedMs' in value) || value['elapsedMs'] === undefined) return false;
    if (!('submittedAt' in value) || value['submittedAt'] === undefined) return false;
    return true;
}

export function SessionsSessionIdPathsPut200ResponseFromJSON(json: any): SessionsSessionIdPathsPut200Response {
    return SessionsSessionIdPathsPut200ResponseFromJSONTyped(json, false);
}

export function SessionsSessionIdPathsPut200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsSessionIdPathsPut200Response {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'path': ((json['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON)),
        'dsl': json['dsl'],
        'elapsedMs': json['elapsedMs'],
        'submittedAt': (new Date(json['submittedAt'])),
    };
}

export function SessionsSessionIdPathsPut200ResponseToJSON(json: any): SessionsSessionIdPathsPut200Response {
    return SessionsSessionIdPathsPut200ResponseToJSONTyped(json, false);
}

export function SessionsSessionIdPathsPut200ResponseToJSONTyped(value?: SessionsSessionIdPathsPut200Response | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'path': ((value['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON)),
        'dsl': value['dsl'],
        'elapsedMs': value['elapsedMs'],
        'submittedAt': value['submittedAt'].toISOString(),
    };
}

