/* tslint:disable */
/* eslint-disable */
/**
 * Maze API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner } from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';
import {
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSONTyped,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON,
    MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSONTyped,
} from './MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner';

/**
 * 
 * @export
 * @interface SessionsSessionIdPatchRequest
 */
export interface SessionsSessionIdPatchRequest {
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPatchRequest
     */
    mazeId: number;
    /**
     * 
     * @type {string}
     * @memberof SessionsSessionIdPatchRequest
     */
    status?: SessionsSessionIdPatchRequestStatusEnum;
    /**
     * 
     * @type {Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>}
     * @memberof SessionsSessionIdPatchRequest
     */
    path?: Array<MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInner>;
    /**
     * 
     * @type {number}
     * @memberof SessionsSessionIdPatchRequest
     */
    elapsedMs?: number;
    /**
     * 
     * @type {Date}
     * @memberof SessionsSessionIdPatchRequest
     */
    expiresAt?: Date | null;
}


/**
 * @export
 */
export const SessionsSessionIdPatchRequestStatusEnum = {
    Created: 'CREATED',
    OnGoing: 'ON-GOING',
    Closed: 'CLOSED'
} as const;
export type SessionsSessionIdPatchRequestStatusEnum = typeof SessionsSessionIdPatchRequestStatusEnum[keyof typeof SessionsSessionIdPatchRequestStatusEnum];


/**
 * Check if a given object implements the SessionsSessionIdPatchRequest interface.
 */
export function instanceOfSessionsSessionIdPatchRequest(value: object): value is SessionsSessionIdPatchRequest {
    if (!('mazeId' in value) || value['mazeId'] === undefined) return false;
    return true;
}

export function SessionsSessionIdPatchRequestFromJSON(json: any): SessionsSessionIdPatchRequest {
    return SessionsSessionIdPatchRequestFromJSONTyped(json, false);
}

export function SessionsSessionIdPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SessionsSessionIdPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'mazeId': json['mazeId'],
        'status': json['status'] == null ? undefined : json['status'],
        'path': json['path'] == null ? undefined : ((json['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerFromJSON)),
        'elapsedMs': json['elapsedMs'] == null ? undefined : json['elapsedMs'],
        'expiresAt': json['expiresAt'] == null ? undefined : (new Date(json['expiresAt'])),
    };
}

export function SessionsSessionIdPatchRequestToJSON(json: any): SessionsSessionIdPatchRequest {
    return SessionsSessionIdPatchRequestToJSONTyped(json, false);
}

export function SessionsSessionIdPatchRequestToJSONTyped(value?: SessionsSessionIdPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'mazeId': value['mazeId'],
        'status': value['status'],
        'path': value['path'] == null ? undefined : ((value['path'] as Array<any>).map(MazesMazeIdDisplayFeedGet200ResponseLeaderboardInnerPathInnerToJSON)),
        'elapsedMs': value['elapsedMs'],
        'expiresAt': value['expiresAt'] == null ? value['expiresAt'] : value['expiresAt'].toISOString(),
    };
}

