/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteRouteImport } from './routes/theory/route'
import { Route as MazeRouteRouteImport } from './routes/maze/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MazeIndexRouteImport } from './routes/maze/index'
import { Route as ImpressumIndexRouteImport } from './routes/impressum/index'
import { Route as TheoryShortestPathIndexRouteImport } from './routes/theory/shortestPath/index'
import { Route as TheoryDslIndexRouteImport } from './routes/theory/dsl/index'
import { Route as MazeAnimationIndexRouteImport } from './routes/maze/animation/index'

const TheoryRouteRoute = TheoryRouteRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeRouteRoute = MazeRouteRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeIndexRoute = MazeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MazeRouteRoute,
} as any)
const ImpressumIndexRoute = ImpressumIndexRouteImport.update({
  id: '/impressum/',
  path: '/impressum/',
  getParentRoute: () => rootRouteImport,
} as any)
const TheoryShortestPathIndexRoute = TheoryShortestPathIndexRouteImport.update({
  id: '/shortestPath/',
  path: '/shortestPath/',
  getParentRoute: () => TheoryRouteRoute,
} as any)
const TheoryDslIndexRoute = TheoryDslIndexRouteImport.update({
  id: '/dsl/',
  path: '/dsl/',
  getParentRoute: () => TheoryRouteRoute,
} as any)
const MazeAnimationIndexRoute = MazeAnimationIndexRouteImport.update({
  id: '/animation/',
  path: '/animation/',
  getParentRoute: () => MazeRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/maze': typeof MazeRouteRouteWithChildren
  '/theory': typeof TheoryRouteRouteWithChildren
  '/impressum/': typeof ImpressumIndexRoute
  '/maze/': typeof MazeIndexRoute
  '/maze/animation/': typeof MazeAnimationIndexRoute
  '/theory/dsl/': typeof TheoryDslIndexRoute
  '/theory/shortestPath/': typeof TheoryShortestPathIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/theory': typeof TheoryRouteRouteWithChildren
  '/impressum': typeof ImpressumIndexRoute
  '/maze': typeof MazeIndexRoute
  '/maze/animation': typeof MazeAnimationIndexRoute
  '/theory/dsl': typeof TheoryDslIndexRoute
  '/theory/shortestPath': typeof TheoryShortestPathIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/maze': typeof MazeRouteRouteWithChildren
  '/theory': typeof TheoryRouteRouteWithChildren
  '/impressum/': typeof ImpressumIndexRoute
  '/maze/': typeof MazeIndexRoute
  '/maze/animation/': typeof MazeAnimationIndexRoute
  '/theory/dsl/': typeof TheoryDslIndexRoute
  '/theory/shortestPath/': typeof TheoryShortestPathIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/maze'
    | '/theory'
    | '/impressum/'
    | '/maze/'
    | '/maze/animation/'
    | '/theory/dsl/'
    | '/theory/shortestPath/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/theory'
    | '/impressum'
    | '/maze'
    | '/maze/animation'
    | '/theory/dsl'
    | '/theory/shortestPath'
  id:
    | '__root__'
    | '/'
    | '/maze'
    | '/theory'
    | '/impressum/'
    | '/maze/'
    | '/maze/animation/'
    | '/theory/dsl/'
    | '/theory/shortestPath/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MazeRouteRoute: typeof MazeRouteRouteWithChildren
  TheoryRouteRoute: typeof TheoryRouteRouteWithChildren
  ImpressumIndexRoute: typeof ImpressumIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze': {
      id: '/maze'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze/': {
      id: '/maze/'
      path: '/'
      fullPath: '/maze/'
      preLoaderRoute: typeof MazeIndexRouteImport
      parentRoute: typeof MazeRouteRoute
    }
    '/impressum/': {
      id: '/impressum/'
      path: '/impressum'
      fullPath: '/impressum/'
      preLoaderRoute: typeof ImpressumIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/theory/shortestPath/': {
      id: '/theory/shortestPath/'
      path: '/shortestPath'
      fullPath: '/theory/shortestPath/'
      preLoaderRoute: typeof TheoryShortestPathIndexRouteImport
      parentRoute: typeof TheoryRouteRoute
    }
    '/theory/dsl/': {
      id: '/theory/dsl/'
      path: '/dsl'
      fullPath: '/theory/dsl/'
      preLoaderRoute: typeof TheoryDslIndexRouteImport
      parentRoute: typeof TheoryRouteRoute
    }
    '/maze/animation/': {
      id: '/maze/animation/'
      path: '/animation'
      fullPath: '/maze/animation/'
      preLoaderRoute: typeof MazeAnimationIndexRouteImport
      parentRoute: typeof MazeRouteRoute
    }
  }
}

interface MazeRouteRouteChildren {
  MazeIndexRoute: typeof MazeIndexRoute
  MazeAnimationIndexRoute: typeof MazeAnimationIndexRoute
}

const MazeRouteRouteChildren: MazeRouteRouteChildren = {
  MazeIndexRoute: MazeIndexRoute,
  MazeAnimationIndexRoute: MazeAnimationIndexRoute,
}

const MazeRouteRouteWithChildren = MazeRouteRoute._addFileChildren(
  MazeRouteRouteChildren,
)

interface TheoryRouteRouteChildren {
  TheoryDslIndexRoute: typeof TheoryDslIndexRoute
  TheoryShortestPathIndexRoute: typeof TheoryShortestPathIndexRoute
}

const TheoryRouteRouteChildren: TheoryRouteRouteChildren = {
  TheoryDslIndexRoute: TheoryDslIndexRoute,
  TheoryShortestPathIndexRoute: TheoryShortestPathIndexRoute,
}

const TheoryRouteRouteWithChildren = TheoryRouteRoute._addFileChildren(
  TheoryRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MazeRouteRoute: MazeRouteRouteWithChildren,
  TheoryRouteRoute: TheoryRouteRouteWithChildren,
  ImpressumIndexRoute: ImpressumIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
