/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TheoryRouteImport } from './routes/theory'
import { Route as MazeRouteImport } from './routes/maze'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MazeIndexRouteImport } from './routes/maze.index'
import { Route as TheoryShortestPathRouteImport } from './routes/theory.shortestPath'
import { Route as TheoryDslRouteImport } from './routes/theory.dsl'
import { Route as MazeAnimationRouteImport } from './routes/maze.animation'

const TheoryRoute = TheoryRouteImport.update({
  id: '/theory',
  path: '/theory',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeRoute = MazeRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeIndexRoute = MazeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MazeRoute,
} as any)
const TheoryShortestPathRoute = TheoryShortestPathRouteImport.update({
  id: '/shortestPath',
  path: '/shortestPath',
  getParentRoute: () => TheoryRoute,
} as any)
const TheoryDslRoute = TheoryDslRouteImport.update({
  id: '/dsl',
  path: '/dsl',
  getParentRoute: () => TheoryRoute,
} as any)
const MazeAnimationRoute = MazeAnimationRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => MazeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/maze': typeof MazeRouteWithChildren
  '/theory': typeof TheoryRouteWithChildren
  '/maze/animation': typeof MazeAnimationRoute
  '/theory/dsl': typeof TheoryDslRoute
  '/theory/shortestPath': typeof TheoryShortestPathRoute
  '/maze/': typeof MazeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/theory': typeof TheoryRouteWithChildren
  '/maze/animation': typeof MazeAnimationRoute
  '/theory/dsl': typeof TheoryDslRoute
  '/theory/shortestPath': typeof TheoryShortestPathRoute
  '/maze': typeof MazeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/maze': typeof MazeRouteWithChildren
  '/theory': typeof TheoryRouteWithChildren
  '/maze/animation': typeof MazeAnimationRoute
  '/theory/dsl': typeof TheoryDslRoute
  '/theory/shortestPath': typeof TheoryShortestPathRoute
  '/maze/': typeof MazeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/impressum'
    | '/maze'
    | '/theory'
    | '/maze/animation'
    | '/theory/dsl'
    | '/theory/shortestPath'
    | '/maze/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/impressum'
    | '/theory'
    | '/maze/animation'
    | '/theory/dsl'
    | '/theory/shortestPath'
    | '/maze'
  id:
    | '__root__'
    | '/'
    | '/impressum'
    | '/maze'
    | '/theory'
    | '/maze/animation'
    | '/theory/dsl'
    | '/theory/shortestPath'
    | '/maze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumRoute: typeof ImpressumRoute
  MazeRoute: typeof MazeRouteWithChildren
  TheoryRoute: typeof TheoryRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/theory': {
      id: '/theory'
      path: '/theory'
      fullPath: '/theory'
      preLoaderRoute: typeof TheoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze': {
      id: '/maze'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze/': {
      id: '/maze/'
      path: '/'
      fullPath: '/maze/'
      preLoaderRoute: typeof MazeIndexRouteImport
      parentRoute: typeof MazeRoute
    }
    '/theory/shortestPath': {
      id: '/theory/shortestPath'
      path: '/shortestPath'
      fullPath: '/theory/shortestPath'
      preLoaderRoute: typeof TheoryShortestPathRouteImport
      parentRoute: typeof TheoryRoute
    }
    '/theory/dsl': {
      id: '/theory/dsl'
      path: '/dsl'
      fullPath: '/theory/dsl'
      preLoaderRoute: typeof TheoryDslRouteImport
      parentRoute: typeof TheoryRoute
    }
    '/maze/animation': {
      id: '/maze/animation'
      path: '/animation'
      fullPath: '/maze/animation'
      preLoaderRoute: typeof MazeAnimationRouteImport
      parentRoute: typeof MazeRoute
    }
  }
}

interface MazeRouteChildren {
  MazeAnimationRoute: typeof MazeAnimationRoute
  MazeIndexRoute: typeof MazeIndexRoute
}

const MazeRouteChildren: MazeRouteChildren = {
  MazeAnimationRoute: MazeAnimationRoute,
  MazeIndexRoute: MazeIndexRoute,
}

const MazeRouteWithChildren = MazeRoute._addFileChildren(MazeRouteChildren)

interface TheoryRouteChildren {
  TheoryDslRoute: typeof TheoryDslRoute
  TheoryShortestPathRoute: typeof TheoryShortestPathRoute
}

const TheoryRouteChildren: TheoryRouteChildren = {
  TheoryDslRoute: TheoryDslRoute,
  TheoryShortestPathRoute: TheoryShortestPathRoute,
}

const TheoryRouteWithChildren =
  TheoryRoute._addFileChildren(TheoryRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumRoute: ImpressumRoute,
  MazeRoute: MazeRouteWithChildren,
  TheoryRoute: TheoryRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
