/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MazeRouteImport } from './routes/maze'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MazeIndexRouteImport } from './routes/maze.index'
import { Route as MazeAnimationRouteImport } from './routes/maze.animation'

const MazeRoute = MazeRouteImport.update({
  id: '/maze',
  path: '/maze',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MazeIndexRoute = MazeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MazeRoute,
} as any)
const MazeAnimationRoute = MazeAnimationRouteImport.update({
  id: '/animation',
  path: '/animation',
  getParentRoute: () => MazeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/maze': typeof MazeRouteWithChildren
  '/maze/animation': typeof MazeAnimationRoute
  '/maze/': typeof MazeIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/maze/animation': typeof MazeAnimationRoute
  '/maze': typeof MazeIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/impressum': typeof ImpressumRoute
  '/maze': typeof MazeRouteWithChildren
  '/maze/animation': typeof MazeAnimationRoute
  '/maze/': typeof MazeIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/impressum' | '/maze' | '/maze/animation' | '/maze/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/impressum' | '/maze/animation' | '/maze'
  id: '__root__' | '/' | '/impressum' | '/maze' | '/maze/animation' | '/maze/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImpressumRoute: typeof ImpressumRoute
  MazeRoute: typeof MazeRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/maze': {
      id: '/maze'
      path: '/maze'
      fullPath: '/maze'
      preLoaderRoute: typeof MazeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maze/': {
      id: '/maze/'
      path: '/'
      fullPath: '/maze/'
      preLoaderRoute: typeof MazeIndexRouteImport
      parentRoute: typeof MazeRoute
    }
    '/maze/animation': {
      id: '/maze/animation'
      path: '/animation'
      fullPath: '/maze/animation'
      preLoaderRoute: typeof MazeAnimationRouteImport
      parentRoute: typeof MazeRoute
    }
  }
}

interface MazeRouteChildren {
  MazeAnimationRoute: typeof MazeAnimationRoute
  MazeIndexRoute: typeof MazeIndexRoute
}

const MazeRouteChildren: MazeRouteChildren = {
  MazeAnimationRoute: MazeAnimationRoute,
  MazeIndexRoute: MazeIndexRoute,
}

const MazeRouteWithChildren = MazeRoute._addFileChildren(MazeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImpressumRoute: ImpressumRoute,
  MazeRoute: MazeRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
